services:
  mariadb:
    volumes:
      - mariadb:/var/lib/mysql
    container_name: phpbb_db
    image: mariadb:10.6.16
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: passwd
      MARIADB_DATABASE: phpbb
    ports:
      - 3311:3306
    networks:
      net:

  phpbb:
    volumes:
      - ./app:/var/www/html
      - /etc/localtime:/etc/localtime:ro
    container_name: phpbb
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
      args:
        UID: ${UID}
        GID: ${GID}
    depends_on:
      - "mariadb"
    networks:
      net:

  webserver:
    volumes:
      - ./app:/var/www/html
      - ./docker/nginx/phpbb.conf:/etc/nginx/conf.d/default.conf
    container_name: phpbb_ws
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - "8383:80"
    depends_on:
      - "phpbb"
    networks:
      net:

networks:
  net:
    name: phpbb-network
    external: false

volumes:
  mariadb:
    name: phpbb-dbdata
